# Naziv aplikacije
spring.application.name=ReceptiApp

# H2 baza podataka se cuva u fajlu
spring.datasource.url=jdbc:h2:file:./data/recepti

# Korisnicko ime baze
spring.datasource.username=sa

# Lozinka je prazna
spring.datasource.password=

# H2 driver
spring.datasource.driver-class-name=org.h2.Driver

# Automatsko kreiranje i azuriranje tabela
spring.jpa.hibernate.ddl-auto=update

# Ukljucuje H2 konzolu
spring.h2.console.enabled=true

# Adresa H2 konzole
spring.h2.console.path=/h2-console